[variables]
PYTHONPATH = "/app"
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p data/uploads logs vector_store"]

[start]
cmd = "python railway_start.py"
