[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"

[env]
PYTHONUNBUFFERED = "1"
